FROM tensorflow/tensorflow:1.14.0-gpu-py3

WORKDIR .

RUN apt-get update
RUN apt-get install -y libsm6 libxext6 libxrender-dev
COPY . .

RUN pip3 install -r requirements.txt
ENTRYPOINT ["python","-u", "evalute_disturb_recog_resnet.py"]