FROM tensorflow/tensorflow:1.14.0-gpu-py3
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN add-apt-repository ppa:deadsnakes/ppa -y ; exit 0
RUN apt-get update
RUN apt install python3.7 libsm6 libxext6 libxrender-dev -y
RUN python3.7 -m pip install --upgrade pip
WORKDIR .

RUN apt-get update
COPY . .

RUN echo $(python -V)

RUN pip install -r requirements.txt
ENTRYPOINT ["python","-u", "evalute_disturb_recog_resnet.py"]